#url 服务器
server:
  tomcat:
      max-threads: 1000
      min-spare-threads: 30
  port: 8089
#spring
spring:
  session:
     store-type: none



# 日志

#com.mycompany.mavenspringboot.controller 日志 WARN级别输出
logging:
  level: debug
  config: classpath:logback.xml










