#url 服务器
server:
  tomcat:
      max-threads: 1000
      min-spare-threads: 30
  port: 8092
#spring
spring:
  session:
     store-type: none
  datasource:
    name: druidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shiro?useUnicode=true&CharacterEncoding=UTF-8
    username: root
    password: 123

    type: com.alibaba.druid.pool.DruidDataSource

# mybaits 配置文件
mybatis:
  mapper-locations: classpath:mapping/*.xml

# 日志

#com.mycompany.mavenspringboot.controller 日志 WARN级别输出
logging:
  level: debug
  config: classpath:logback.xml










