##############################################
##################  spring  #################
##############################################
spring:
  profiles:
    active: pro
##############################################
##################  strWhite  #################
##############################################
strWhite: /api/user/login;
##############################################
##################  mybatis  #################
##############################################
mybatis:
  mapper-locations: classpath:mapping/*.xml

##############################################
##################  log  #################
##############################################
logging:
  file: classpath:logs/spring-boot-logging.logs
  level:
    root: debug




