#url 服务器
server:
    tomcat:
        max-threads: 1000
        min-spare-threads: 30
    port: 8092


#spring
spring:
  #thymeleaf模板
  thymeleaf:
      cache: false

   # h2 嵌入式数据库
  jpa:
    database: H2
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: sa
  # 不使用redis存储则需要配置为none
  session:
    store-type: none
    #schema: classpath:/db/data.sql



# mybaits 配置文件
mybatis:
  mapper-locations: classpath:mapping/*.xml

# 日志

#com.mycompany.mavenspringboot.controller 日志 WARN级别输出
logging:
  level: debug
  config: classpath:logback.xml










