########################################################
### spring 相关配置
########################################################
spring:
  # 暂不设置缓存
  session:
    store-type: none

  ############################# ###########################
  ### datasource
  ########################################################
  datasource :
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://xxx?characterEncoding=UTF-8&allowMultiQueries=true
    username: xx
    password: xx
    
    # 初始化大小，最小，最大
    max-idle: 500
    min-idle: 2

    #最大等待实际为10秒
    max-wait: 10000
    test-while-idle: true
    test-on-borrow: false

    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    time-between-eviction-runs-millis: 18800

    # 验证
    validation-query: select 1


    
  #############定义日志输出色彩
  output:
    ansi:
      enabled: DETECT

# thymeleaf 相关配置
  thymeleaf:
    cache: false
  application:
    name: test






########################################################
### mybatis配置
########################################################
mybatis :
  mapper-locations: classpath:/mapping/*.xml
  configuration:
    mapUnderscoreToCamelCase: true
    callSettersOnNulls: true
########################################################
#####################其它配置###########################
########################################################


logging:
  level: debug
  config: classpath:logback.xml

server:
  context-path: /
  port: 8087
  tomcat.max-threads: 0
  compression.enabled: true
  undertow.accesslog.enabled: true



