########################################################
### spring 相关配置
########################################################
spring:
  # 暂不设置缓存
  session:
    store-type: redis

  ############################# ###########################
  ### datasource
  ########################################################
  datasource :
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.17.42.222:3306/cis_credit?characterEncoding=UTF-8&allowMultiQueries=true
    username: dev_cis_credit
    password: Utu2ir^diYe!@1jHH

    # 初始化大小，最小，最大
    max-idle: 500
    min-idle: 2

    #最大等待实际为10秒
    max-wait: 10000
    test-while-idle: true
    test-on-borrow: false

    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    time-between-eviction-runs-millis: 18800

    # 验证
    validation-query: select 1

  ########################################################
  ###redis
  ########################################################


  redis:
    cluster:
      max-redirects: 3
      nodes: 172.17.46.11:36379,172.17.45.12:36379,172.17.45.13:36379
    pool:
      max-active: 100
      max-idle: 10
      max-wait: 500
      timeout: 200

  #############定义日志输出色彩
  output:
    ansi:
      enabled: DETECT

# thymeleaf 相关配置
  thymeleaf:
    cache: false
  application:
    name: test






########################################################
### mybatis配置
########################################################
mybatis :
  mapper-locations: classpath:/mapping/*.xml
  configuration:
    mapUnderscoreToCamelCase: true
    callSettersOnNulls: true
########################################################
#####################其它配置###########################
########################################################


logging:
  level: debug
  config: classpath:logback.xml

server:
  context-path: /
  port: 8081
  tomcat.max-threads: 0
  compression.enabled: true
  undertow.accesslog.enabled: true



