##############################################
##################  tomcat  #################
##############################################
server:
    tomcat:
        max-threads: 1000
        min-spare-threads: 30
    port: 8091


##############################################
##################  spring  #################
##############################################
spring:
  session:
    store-type: none

  #druid数据源
  datasource:
    name: druidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shiro?useUnicode=true&CharacterEncoding=UTF-8&useSSL=false
    username: root
    password: 123

    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
########################################################
### logback 配置
########################################################
logging:
  level: debug
  config: classpath:logback.xml






