##############################################
##################  spring  #################
##############################################
spring:
  profiles:
    active: dev
##############################################
##################  strWhite  #################
##############################################
strWhite: /api/user/login,/userInfo/list,/userInfo/obj;
##############################################
##################  mybatis  #################
##############################################
mybatis:
  mapper-locations: classpath:mapping/*.xml






